targets:
  $default:
    builders:
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: capstone_laundry_client|lib/src/schema.graphql
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: capstone_laundry_client|lib/src/schema.graphql
          