targets:
  $default:
    builders:
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: capstone_laundry_client|lib/src/schema.graphql
          custom_serializers:
            - import: "package:path/to/date_serializer.dart"
              name: DateSerializer

      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: capstone_laundry_client|lib/src/schema.graphql
          